const PregWeeks = [
    {
        id: 4,
        title: "week-4",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-4-yolk-sac_4x3.png?width=1026",
        heading: "Week 4",
        message: "At 4 weeks, your baby is an embryo made up of two layers, and your primitive placenta is developing",
        fruit: "https://assets.babycenter.com/ims/2020/11/4-weeks-poppy-seeds_wide.jpg?width=722",
        size: "Your baby is the size of a poppy seed",
        development:"By the end of this week, you may be able to get a positive pregnancy test. Pregnancy tests work by detecting the presence of a hormone called human chorionic gonadotropin (hCG) in your urine.  Due Date Calculator can determine your due date based on the date of your last menstrual period or the date of conception. Keep in mind that a due date is just a guess – only 1 out of 20 women actually delivers on her due date. Now that your little embryo has implanted in your uterus, cells are multiplying rapidly and taking on different functions. Your baby-to-be consists of two layers (called the hypoblast and the epiblast) from which all of the organs will begin to develop over the next six weeks. ",
        mom: "This is the time when your baby will be most vulnerable to anything that might interfere with development, so be sure to steer clear of alcohol, smoking, drugs, and unsafe chemicals. Also, watch out for overheating. High temperatures, especially early in pregnancy, have been associated with increased risk of neural tube defects. That's why saunas, steam baths, and hot tubs aren't recommended during pregnancy.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/be8d725008372cc5db28ea3cadb4d108-615x410.jpg",
        textus: "It's Week 4 of your pregnancy, you've technically only been pregnant for two weeks.  Ultrasound not able to detect the developing embryo yet.(Don't panic!)"
    },
    {
        id: 5,
        title: "week-5",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-5-amniotic-sac_4x3.png?width=396",
        heading: "Week 5",
        message: "At 5 weeks, your tiny embryo growing like crazy, and you may be noticing pregnancy discomforts like sore breasts and fatigue.",
        fruit: "https://assets.babycenter.com/ims/2020/11/5-weeks-sesame-seeds_wide.jpg?width=722",
        size: "Your baby is about the size of a sesame seed",
        development: "Deep in your uterus an embryo is growing at a furious pace, and it looks more like a tadpole than a human. When you're 5 weeks pregnant, a tiny tube-like structure is beginning to develop into your baby's heart, though he almost certainly has his grip on yours already! Also in the works this week are several other organs, including the neural tube — the precursor to your baby's brain and spinal cord — which hasn't yet sealed. ",
        mom: "Increased hormone levels boost blood flow, which may make your breasts feel swollen and sore, you may feel constant need to pee and bone-crushing exhaustion.Morning sickness – also called nausea and vomiting of pregnancy – affects different expecting moms at different times (and some not at all). It usually starts around week 5 or 6 of pregnancy.  Ultrasound not able to detect the developing embryo yet.(Don't panic!)",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/59fdde24ecc10bbcd35029ab62e09b02-615x410.jpg",
        textus: "The embryo is now about two millimetres long and usually still not visible on the ultrasound. Nevertheless, the embryo's heart begins to beat this week."
    },
    {
        id: 6,
        title: "week-6",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-6-webbed-hands_4x3.png?width=1026",
        heading: "Week 6",
        message: "At 6 weeks, your baby's heart has started beating. You may have morning sickness and sore breats.",
        fruit: "https://assets.babycenter.com/ims/2020/11/6-weeks-lentil_wide.jpg?width=722",
        size: "Your little lentil is now about 1/4 inch long.",
        development: "Your baby's heart isn't fully developed, but cells in the heart tube have started beating fast, around 160 times a minute. You may hear the sound this week if you have an early ultrasound.",
        mom: "One in four women have some bleeding during this trimester. If you do, call your healthcare provider and get it checked out. You might be coping with full-blown pregnancy symptoms, but there's plenty of good news too. The folds of tissue in the prominent bump on top — the head — are developing into your baby's jaw, cheeks and chin, which will eventually become one adorable face.Small dots on the face will form the eyes and button nose in a few weeks.Also taking shape this week: your baby's kidneys, liver and lungs, along with his little heart. You may notice a metallic taste in your mouth during the first trimester thanks to a surge in estrogen. It's common to get headaches during pregnancy, especially in the first trimester.Many pregnant women find that moodiness flares up around 6 to 10 weeks.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/cd58af448c02f9087337f90301efaeca-615x410.jpg",
        textus: "The embryo is now about four millimetres long and the head and neck are already formed."
    },
    {
        id: 7,
        title: "week-7",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-7-tailbone_4x3.png?width=1026",
        heading: "Week 7",
        message: "At 7 weeks, your baby's eyes, nose, mouth, and ears are taking shape. You may need to pee constantly.",
        fruit: "https://assets.babycenter.com/ims/2020/11/7-weeks-blueberry_wide.jpg?width=722",
        size: "Your baby has doubled in size since last week and is now about 1/2 inch long and now it's a size of a blueberry",
        development: "The main parts of the eye that allow your baby to see – the cornea, iris, pupil, lens, and retina – start developing this week, and they're almost fully formed just a few weeks later.Your baby's stomach, liver and pancreas start to form. The neural tube that becomes your baby's spinal column and brain has formed and closed on both ends, with your baby's brain at the top. Arm and leg buds are growing longer.",
        mom: "Some foods to avoid now : Swordfish, cold deli meats, raw oysters, homemade cookie dough, bean sprouts, extra-large coffees, unpasteurized juices, and queso fresco. Many newly pregnant women find that they're overwhelmed by gag-inducing smells. This may be a side effect of rapidly increasing levels of estrogen in your system. You may suddenly find that certain foods you used to enjoy are now completely repulsive to you.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/68dd37dd94587b4b07d2d237bb6a201f-615x410.jpg",
        textus: "You can see here the amniotic sac, which is about five millimetres long, with a bean-shaped curved embryo visible."
    },
    {
        id: 8,
        title: "week-8",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-8-brain-nerve-cells_4x3.png?width=1026",
        heading: "Week 8",
        message: "At 8 weeks, your baby's hands and feet are sprouting webbed fingers and toes You may have nausea and fatigue.",
        fruit: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-8-brain-nerve-cells_4x3.png?width=1026",
        size: "Your little bean is about 0.62 inch head to bottom, 0.71 ounces, and is constantly moving and shifting.",
        development: "Your baby is moving! These first movements are more like spontaneous twitches and stretches. They start at about 7 to 8 weeks and are visible on ultrasound. You won't feel your baby move until sometime between 16 and 22 weeks, though. Until then, your baby's movements aren't strong enough for you to notice.Your baby's respiratory system is forming.A network of nerves is spreading through your baby's body, making connections not only with each other but also with muscles and other tissues, as well as organs like the eyes and ears.",
        mom: "You may notice an increase in white creamy discharge early in pregnancy, due to higher levels of estrogen. White vaginal discharge (called leucorrhea) is nothing to worry about. Rising levels of hormones cause your breasts to grow in preparation for making breast milk.You might feel like you have a superhuman sense of smell right now. Unfortunately, most of what you're smelling may make you want to throw up. Headaches are common during pregnancy due to factors including increased blood flow and fatigue. Cutting back on caffeine during pregnancy, though important, can also lead to an aching head. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/a71677c4dfc22ed74370d1a96f1b1b83-615x410.jpg",
        textus: "The embryo now measures about 15 millimetres. It can be seen here from the front – the head is to the left in the picture."
    },
    {
        id: 9,
        title: "week-9",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-9-finger-touch-pads_4x3.png?width=1026",
        heading: "Week 9",
        message: "At 9 weeks, your baby start looking more like a human. This is peak morning sickness time. You might experience a heartburn. ",
        fruit: "https://assets.babycenter.com/ims/2020/11/9-weeks-grape_wide.jpg?width=722",
        size: "Your baby now weighs almost an ounce and is almost 1 inch long. ",
        development: `Your baby has all the essential body parts now, including elbows and knees. On your baby's face, the upper lip, nose, and eyelids have formed. And your baby's tiny toes are visible! Ten tiny tooth buds are developing within each band of gums. The four chambers of your baby's heart have formed. If you expect to hear the familiar, steady "lub-dub" sound of a human heartbeat at a prenatal appointment, you're in for a surprise. `,
        mom: "Your body is not only growing a new baby, but also a new organ – the placenta, which is attached to your uterus and connected to your baby through the umbilical cord. Your placenta is developed enough now to take over most of the critical job of producing hormones that help your baby grow and develop. Up to half of pregnant women will have constipation during pregnancy. Keep things moving with plenty of water and high-fiber foods like fruits and vegetables, beans, and whole grains. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/86510371190ce77c73c7db2c4acd8272-615x410.jpg",
        textus: "The embryo is about two inches long in the 9th week of pregnancy. The small tail regresses now, and the ears are slowly being revealed. The fetus here is pictured with the head lowered towards the chest."
    },
    {
        id: 10,
        title: "week-10",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-10-fingernails_4x3.png?width=1026",
        heading: "Week 10",
        message: "At 10 weeks, you baby has finished the most critical part of the development! You might be ready for maternity clothes, or at least some new bras.",
        fruit: "https://assets.babycenter.com/ims/2020/11/10-weeks-kumquat_wide.jpg?width=722",
        size: "Your baby is about the size of a kumquat and it weighs a little over an ounce and is a little over 1 inch long from head to bottom.",
        development: `The main parts of the eye that enable your baby's vision – the cornea, iris, pupil, lens, and retina – are fully formed. Eyelids cover your baby's eyes, and they'll stay shut until you're 27 weeks pregnant. Your baby's teeth are starting to harden and connect to the jaw bone. A few babies are born with a tooth or two, but most don't sprout a first tooth until 6 to 10 months old. Your baby's forehead temporarily bulges with their developing brain and sits very high on their head, which measures half the length of their body. Synapses in your baby's spinal cord allow them to move their limbs and fingers. `,
        mom: "You might be noticing blue, prominent veins across your chest, breasts, and belly. As your body produces more blood to support your pregnancy, your veins enlarge and are more visible. You may also develop varicose veins in your legs and lower body as your uterus grows. The good news: They often disappear or improve after you give birth.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/2e93262c628c98556c50e0fea9d2b837-615x410.jpg",
        textus: "At 10 weeks, the fetus measures approximately 2.5 centimetres. The head is still huge in size compared to the rest of the body. In this picture, the head is still inclined towards the chest, but soon it'll gradually begin to raise."
    },
    {
        id: 11,
        title: "week-11",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-11-tooth-buds_4x3.png?width=1026",
        heading: "Week 11",
        message: "At 11 weeks, your baby is busy kicking and stretching. But you won't feel it for a while yet.",
        fruit: "https://assets.babycenter.com/ims/2020/11/11-weeks-fig_wide.jpg?width=722",
        size: "Your baby is about the size of a fig, about 1.6 inches, and 1.6 ounces",
        development: `Your baby's tiny fingers and toes have lost their webbing and are distinct – and longer. As you reach the end of the first trimester, all your baby's vital organs are in place, and many have already started to function. The liver is making red blood cells, kidneys are making urine, and the pancreas starts making insulin. The four chambers of your baby's heart are fully formed, and your baby's heart is beating.By the end of this week, your baby's genitals will start developing. The external sex organs – the penis and scrotum in boys, the clitoris and labia in girls – don't start to differ from each other until about 11 weeks..`,
        mom: " Constipation, gas, and bloating are all common during pregnancy due partly to hormonal changes, which can slow digestion.There's no way around it, your life changes profoundly when you have a baby. You may be excited for the changes, slightly nervous, or anxious – depending on the day. Be sure to prioritize rest, plan healthy meals, exercise safely, and share your feelings with someone you trust. By taking care of yourself, you're also taking care of your baby",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/bdddd55698b2d5ff8ba74923c1e775de-615x410.jpg",
        textus: "On this ultrasound image, only the legs of the fetus are shown. They are bent at the knees at a right angle, the feet pointing upwards. The feet are already clearly developed."
    },
    {
        id: 12,
        title: "week-12",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-12-eyelids_4x3.png?width=1026",
        heading: "Week 12",
        message: "Your baby can curl those tiny toes and make sucking movements.",
        fruit: "https://assets.babycenter.com/ims/2020/11/12-weeks-lime_wide.jpg?width=722",
        size: "Your baby is about the size of a lime",
        development: `The stomach and esophagus started forming around 7 weeks of pregnancy, and your baby's intestines grew so fast that they protruded into the umbilical cord. Soon, the abdominal wall will close and their intestines will make their way inside their abdomen.`,
        mom: "Dizziness in pregnancy happens because your cardiovascular system undergoes dramatic changes: Your heart rate goes up, your heart pumps more blood per minute, and the amount of blood in your body increases by 30 to 50 percent. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/905c69755777d3025a0f941d153bdf60-615x410.jpg",
        textus: "Here you can see the head and part of the upper body. You can see the skull bone and the jaw and teeth.The small nose and mouth are clearly visible at the end of the first trimester, even though the fetus measures only five centimetres."
    },
    {
        id: 13,
        title: "week-13",
        image: "https://assets.babycenter.com/ims/2018/06/pregnancy-week-13-fingerprints_4x3.png?width=1026",
        heading: "Week 13",
        message: "At 13 weeks, you are in the last week of the first trimester. Your baby now has exquisite fingerprints and it almost 3 inches long",
        fruit: "https://assets.babycenter.com/ims/2020/11/13-weeks-pea-pod_wide.jpg?width=722",
        size: "Your baby is about the size of a peapod",
        development: `Your baby has started swallowing amniotic fluid and excreting urine, recycling the full volume of fluid every few hours. Bones are beginning to harden in your baby's skeleton, especially longer bones and the skull. Your baby's teeth and bones are becoming denser.`,
        mom: "Occasional cramping during pregnancy is common. It could be caused by anything from gas and bloating to round ligament pain. Sometimes a little movement, a hot bath or shower, drinking more fluids, or lying down can do the trick to ease abdominal pain. Are you congested lately? Nearly one-third of pregnant women get a stuffy nose due to hormones and increased blood volume.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/d11140ef1d947dc8582dae69f0e81f1c-615x410.jpg",
        textus: "On this picture you can see the head of the fetus from the top. The two halves of the brain are clear to see."
    },
    {
        id: 14,
        title: "week-14",
        image: "https://assets.babycenter.com/ims/2018/06/14-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 14",
        message: "Your baby is now making expressions with its tiny features. At 14 weeks, you may be feeling more energetic and less nauseated.",
        fruit: "https://assets.babycenter.com/ims/2020/11/14-weeks-lemon_wide.jpg?width=722",
        size: "Your baby is about the size of a lemon, measuring 5.8 in",
        development: `Soft baby hair is coming: Hair follicles have started to form deep in your baby's skin. Around 20 weeks, fine downy hair will sprout from these follicles on your baby's eyebrows, upper lip, and chin.Though you can't feel those tiny punches and kicks yet, your baby is quite active and has flexible hands and feet.`,
        mom: "Your energy is likely returning, and your queasiness may have eased by now. If not, hang on – chances are good that morning sickness will soon be behind you if it's not already. The top of your uterus is a bit above your pubic bone, which may be enough to push your tummy out a tad. On either side of your uterus, you have two ligaments that stretch and thicken to accommodate your growing belly. These changes may cause round ligament pain. It can feel like a short, stabbing pain in response to movement, or a dull ache after an especially active day. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/ed4eb375e4011025abb4cf3182fb5621-615x410.jpg",
        textus: "In this picture you can see a twin pregnancy at 14 weeks, with two gestational sacs clearly visible."
    },
    {
        id: 15,
        title: "week-15",
        image: "https://assets.babycenter.com/ims/2018/06/15-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 15",
        message: "At 15 weeks, you baby can move joints and is forming taste buds. Have a stuffy nose? It's a surprising pregnancy side effect!",
        fruit: "https://assets.babycenter.com/ims/2020/11/15-weeks-apple_wide.jpg?width=722",
        size: "Your baby is about the size of an apple, 6.6 in long and weights about 4 oz",
        development: `Your baby is forming taste buds, and nerves begin connecting them to the brain. By about 20 weeks, your baby's taste buds will be fully formed.Your baby's legs are growing longer than their arms now, and they can move all of their joints and limbs. Your active baby is moving constantly, though you can't feel it yet.Your baby is looking more like a little person, with eyelids, eyebrows, eyelashes, nails, hair, and well-defined fingers and toes. `,
        mom: "If your nose is stuffed up, you can probably chalk it up to the combined effect of hormonal changes and increased blood flow to your mucous membranes. This condition is so common there's even a name for it: rhinitis of pregnancy. Keep the tissues handy: About 20 percent of pregnant women have nosebleeds thanks to increased blood volume and blood vessel expansion in the nose. These are usually harmless, but tell your provider if you have frequent nosebleeds.Hopefully you've said goodbye to first-trimester nausea and food aversions and can start enjoying food again. If you started pregnancy at a healthy weight, you'll aim to gain about a pound a week for the rest of your pregnancy.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/64eae657af1f798df9b3c897cb1872b6-615x410.jpg",
        textus: "The image shows the leg of the fetus. The long bones in the upper and lower legs are clearly distinguishable already, as are the toe bones in the foot."
    },
    {
        id: 16,
        title: "week-16",
        image: "https://assets.babycenter.com/ims/2018/06/16-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 16",
        message: "At 16 weeks pregnant, you may be having less nausea and fewer mood swings. Your baby is heading into a growth spurt.",
        fruit: "https://assets.babycenter.com/ims/2020/11/16-weeks-avocado_wide.jpg?width=722",
        size: "Your baby is about the size of an avocado",
        development: `Your baby's skin is thin and translucent. It will thicken and develop as your pregnancy progresses, but will continue to be almost transparent for quite some time.On your baby's scalp, hair follicles are forming a pattern that will remain for life. This patterning sets the stage for how your baby's hair will grow. Your baby's heart is now pumping about 25 quarts of blood each day, and this amount will continue to increase as your little one develops.`,
        mom: `Glowing skin during pregnancy isn't a myth – it's a real thing that happens thanks to fluctuating hormone levels and increased blood flow. You're most likely to have a pregnancy glow in the second trimester.Is "pregnancy brain" real? Researchers aren't sure, but many moms-to-be report having moments of absentmindedness and trouble focusing. No one knows exactly why this happens, but it seems likely that a combination of stress and anxiety, fatigue, and hormones could lead to forgetfulness during pregnancy. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/c29bc868b74af4d9d30fda8c00cd4abc-615x410.jpg",
        textus: "On the ultrasound image, the umbilical cord can be seen. It supplies the baby with nutrients and oxygen and carries away waste products."
    },
    {
        id: 17,
        title: "week-17",
        image: "https://assets.babycenter.com/ims/2018/06/17-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 17",
        message: "At 17 weeks, your baby's skeleton is changing, from soft cartilage to bone and the umbilical cord is growing stronger and thicker",
        fruit: "https://assets.babycenter.com/ims/2020/11/17-weeks-turnip_wide.jpg?width=722",
        size: "Your baby is about the size of a turnip and weights about 6.5 oz",
        development: `Between 16 and 22 weeks, your baby will start to hear sounds inside your body, including the noises made by your heartbeat, breathing, and digestion.Your baby's skeleton is changing from soft cartilage to bone. Support your baby's bone health (and your own) by eating calcium-rich foods. Getting enough calcium also reduces your risk of hypertension and preeclampsia.Sweat glands are starting to develop. And by next week, the layers of your baby's skin will be fully formed.`,
        mom: "You may notice your vision seems blurrier and your eyes are drier. Strange though this seems, vision changes are common during pregnancy. Mild itching is a normal pregnancy skin problem. You may feel it especially around your breasts and belly where the skin is stretching a lot. Sometimes eczema worsens during pregnancy, also making for itchiness.For relief, try applying an ice pack or a cold compress to the itchy area, moisturize using fragrance-free lotion (refrigerate the lotion first for extra cooling), or take a warm oatmeal bath. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/4cc8da69ac6740f97a84d91d2d4934d4-615x410.jpg",
        textus: "On this 3D ultrasound scan, you can already clearly see a little face has formed. The baby now measures about 12cm from crown to rump."
    },
    {
        id: 18,
        title: "week-18",
        image: "https://assets.babycenter.com/ims/2018/06/18-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 18",
        message: "Your baby's genetals are developed enough to see on ultrasound. Hungry? An increase in appetite is normal at 18 weeks pregnant.",
        fruit: "https://assets.babycenter.com/ims/2020/11/18-weeks-bellpepper_wide.jpg?width=722",
        size: "Your baby is about the size of a bell pepper",
        development: "Your baby's ears, nose, and lips are all recognizable on an ultrasound. Eyelids, eyebrows, eyelashes, nails, and hair are formed, too! In your baby's lungs, the smallest tubes (bronchioles) start to develop. At the end of these tiny tubes, respiratory sacs begin to appear. By the time your baby is born, these sacs will become enmeshed with tiny blood vessels that allow oxygen and carbon dioxide to flow in and out." ,
        mom: `Are you feeling your baby move? If not, it may happen soon. The first movements often feel like little flutters, gas bubbles, or even like popcorn popping. Leg cramps during pregnancy are a bit of a mystery, though they're thought to be connected to swelling and the extra weight you're carrying, which requires your leg muscles to work harder. It's normal to have swelling in your feet and ankles during pregnancy, as well as mild swelling in your hands and fingers. (If your rings are getting tight, take them off now!) Sometimes, sudden and severe swelling can signal a more serious issue. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/aeed739ed463064882b8db5c679cbfba-615x410.jpg",
        textus: "You can see here both hands - A hand is coming from the top right in the picture, the fingers of both hands fan out to the left."
    },
    {
        id: 19,
        title: "week-19",
        image: "https://assets.babycenter.com/ims/2018/06/19-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 19",
        message: "At 19 weeks, hair is sprouting on your baby's scalp. If your sides are aching, it could be round ligament pain.",
        fruit: "https://assets.babycenter.com/ims/2020/11/19-weeks-tomato_wide.jpg?width=722",
        size: "Your baby is almost 10 inches and about the size of an heirloom tomato",
        development: `The skin on your baby's fingers and toes has formed distinct patterns. These fingerprints (and toeprints) are now permanent and unique – even among identical twins!A white, waxy coating called vernix caseosa is forming on your baby's skin. Vernix has many benefits: It protects and moisturizes your baby's skin, protects against harmful bacteria, and helps the lungs and digestive tract develop.`,
        mom: `Are the palms of your hands red? It's from extra estrogen. You may also have patches of darkened skin on your upper lip, cheeks, and forehead – that's called melasma, or the "mask of pregnancy." Feeling out of breath lately? You're not imagining it – you need more oxygen during pregnancy, and your body adapts by inhaling and exhaling more air with each breath. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/ec4f0e67e50fc53384a62eab182efc3c-615x410.jpg",
        textus: "The fetus is not seen in this picture, but rather the placenta (the entire grey area at the bottom), from which springs the umbilical cord."
    },
    {
        id: 20,
        title: "week-20",
        image: "https://assets.babycenter.com/ims/2018/06/20-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 20",
        message: "At 20 weeks, you're half mark at your pregnancy - congrats! Your baby's taste buds are now working.",
        fruit: "https://assets.babycenter.com/ims/2020/11/20-weeks-banana_wide.jpg?width=722",
        size: "Your burgeoning baby now measures about 10 inches from head to heel, and weighs roughly 11 1/2 ounces.",
        development: `If you notice some baby movements that feel like subtle, rhythmic jerking, don't worry – baby hiccups in the womb are totally normal. Many of your baby's taste buds can now transmit taste signals to their brain, and your baby is swallowing molecules of the food you eat that have passed through your blood into your amniotic fluid. `,
        mom: "You may feel especially itchy around your belly and breasts as your skin stretches to accommodate your growing baby. Finally, some enjoyable pregnancy symptoms! You may be noticing you have longer nails and thicker hair at this point. Hair often gets thicker during pregnancy – not because you're growing more, but because estrogen makes the growth phase longer. Basically, you're losing less hair. All the hair you didn't lose during pregnancy will start shedding about three to five months after delivery. It's normal, but postpartum hair loss can come as a surprise. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/4a3f94c1a8a173464100ce8104846aba-615x410.jpg",
        textus: "In this 3D ultrasound image, the baby seems to be sucking the thumb of his left hand"
    },
    {
        id: 21,
        title: "week-21",
        image: "https://assets.babycenter.com/ims/2018/06/21-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 21",
        message: "Feeling your baby move at 21 week pregnant? Those early flutters will turn into full-fledged kicks. cool fact: your baby has eyebrows now",
        fruit: "https://assets.babycenter.com/ims/2020/11/21-weeks-carrot_wide.jpg?width=722",
        size: "Your carrot-sized cutie is now a little over 10 1/2 inches from head to heel and weighs about 14 ounces.",
        development: `Your baby has working taste buds and can taste what you eat when they swallow your amniotic fluid. Your baby's sucking reflex is starting to develop, and your baby can suck their thumb. Smooth, gorgeous skin is in your baby's future – but for now, their skin is wrinkled and translucent. It appears red because of visible blood vessels.`,
        mom: `You're more prone to varicose veins now. As your pregnancy progresses, the weight of your uterus puts increasing pressure on the veins in your legs. Braxton Hicks are "practice" uterine contractions that are mostly infrequent, irregular, and painless. They start early in pregnancy, but you probably won't start feeling them until around 21 weeks. (Some women never notice them, and that's okay, too.). It's most common to have Braxton Hicks contractions at the end of the day, when you're dehydrated or have a full bladder, or during or after physical activities including sex. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/060c53dfd3a6a07e26af94388fc3c101-615x410.jpg",
        textus: "You can clearly see two little feet in this scan picture, fully formed at 21 weeks."
    },
    {
        id: 22,
        title: "week-22",
        image: "https://assets.babycenter.com/ims/2018/06/22-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 22",
        message: "At 22 weeks, you baby may be able to hear your heatbeat and your growing belly may be turning into a hand-magnet.",
        fruit: "The baby's facial profile can be clearly seen in this image.",
        size: "Your baby is about the size of a spaghetti squash",
        development: `At 11 1/2 inches and a little over 1 pound, your baby is starting to look like a miniature newborn as their lips, eyelids, and eyebrows become more distinct. Baby hair is visible on your little one's head. It's thin now, but may be thick and lustrous by the end of pregnancy. Your baby may be able to hear sounds from inside your body, such as noises from your breathing, heartbeat, and digestion. These sounds will grow louder as your baby's hearing improves. `,
        mom: "Pregnancy acne is very common, and can strike even if you've never had pimples before. (Pregnancy-related hormone changes are probably to blame.) Before using any acne medication, talk to your provider or a dermatologist to make sure it's safe for pregnancy. It's normal to have some pregnancy swelling, also called edema. You're retaining more water, your blood chemistry is moving more fluid into your tissues, and your growing uterus is putting pressure on major veins, slowing down the return of blood from your legs. You may start having leg cramps during your second trimester, especially at night when you're trying to sleep. Leg cramps could be due to the extra weight your body is carrying around, or they could be related to pregnancy swelling.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/d5e9f8b7a977b012f9a375086233c5a9-615x410.jpg",
        textus: "The baby's facial profile can be clearly seen in this image."
    },
    {
        id: 23,
        title: "week-23",
        image: "https://assets.babycenter.com/ims/2018/06/23-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 23",
        message: "Now that you are 23 weeks pregnant, you baby has a weel-developed sense of movement. Meanwhile, you may notice swelling in your ankles and feet.",
        fruit: "https://assets.babycenter.com/ims/2020/11/23-weeks-mango_wide.jpg?width=722",
        size: "Your baby is about the size of a large mango; it now weighs about 1 1/4 pounds and is more than a foot long",
        development: `Your baby can hear sounds from outside your body now, such as your voice or your partner's. Research shows babies learn to recognize their mother's voice inside the womb, and show a clear preference for her voice over others. The wave-like movements that propel food along your baby's digestive tract begin now. As with swallowing, it's just practice for your baby's system at this point since there's no actual food to move.`,
        mom: "Also called the pregnancy line, the linea nigra is a dark, vertical line most pregnant women develop on their growing baby bump during their second trimester. Higher-than-usual levels of hormones act on the cells that contain melanin, which gives your skin its color. (Fun fact: You always have the line down your belly, but it's usually not visible.) After your pregnancy, the linea nigra should fade over a few weeks to months, though in some women it may not disappear entirely.Now that your appetite has likely returned (perhaps stronger than ever), you might be having intense cravings. Most women will crave at least one specific food during pregnancy, and many crave a variety of different foods. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/6853c8f5c2c616bc4dfd0bd58cccedb8-615x410.jpg",
        textus: "In this 3D image of a 23-week old fetus, the baby seems to be yawning!"
    },
    {
        id: 24,
        title: "week-24",
        image: "https://assets.babycenter.com/ims/2018/06/24-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 24",
        message: "At 24 weeks, you baby is still long and lean - but that will soon change.Your growing uterus is now the size of a soccer ball.",
        fruit: "Now that your appetite has likely returned (perhaps stronger than ever), you might be having intense cravings. Most women will crave at least one specific food during pregnancy, and many crave a variety of different foods. ",
        size: "Your baby is now about 12 1/2 inches long from head to heel and weighs nearly 1 1/2 pounds.",
        development: `Respiratory sacs at the tips of the smallest branches of your baby's lungs are growing and multiplying, adding more surface area for the exchange of oxygen and carbon dioxide.Your baby cuts a pretty lean figure at this point, but their body is filling out proportionally, and soon they'll start to plump up. Their skin is still thin and translucent. Tiny eyebrows grew on your baby's face just a few weeks ago. Now your baby may practice working their facial muscles and raising them.`,
        mom: `If you're experiencing new skin symptoms, like itchiness, hyperpigmentation, raised bumps, or hives, check in with your doctor or midwife. Most rashes during pregnancy are related to allergies, contact dermatitis (contact with an irritant), or skin infections – they're not caused by pregnancy. During the second trimester, some women experience spotting or light bleeding during pregnancy. This could be caused by changes to your cervix, inflammation, or a benign cervical polyp. Spotting during the second trimester is typically harmless. However, if you experience regular, heavier bleeding, seek medical attention right away. Dramatic mood swings may have faded at 24 weeks pregnant – but it's perfectly normal to have them during the second trimester. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/7c1f29e4a3d4bfb7f7d98a76e7bff610-615x410.jpg",
        textus: "You can quite clearly see the hand and finger bones. By this stage of pregnancy, the baby can now explore his surroundings, suck his thumbs or play with his umbilical cord."
    },
    {
        id: 25,
        title: "week-25",
        image: "https://assets.babycenter.com/ims/2018/06/25-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 25",
        message: "At 25 weeks, your liitle one starting to add some baby fat and growing more hair. Your hair may be looking  extra lustrous.",
        fruit: "https://assets.babycenter.com/ims/2020/11/25-weeks-rutabaga_wide.jpg?width=722",
        size: "Your baby now rivals the average rutabaga in weight – about 1 3/4 pounds – and is roughly 13 1/4 inches long from head to heel.",
        development: `Your baby spends most of their time sleeping, and cycles between rapid eye movement (REM) sleep and non-REM sleep every 20 to 40 minutes. Your baby is growing more hair – and if you could see it, you'd be able to discern its color and texture.`,
        mom: `Also called pelvic girdle pain, pubic symphysis dysfunction (SPD) can strike as your body prepares to give birth. The ligaments surrounding joints in your pelvic area become more relaxed and flexible – and may stretch too far or allow pelvic bones to move too easily. This change, coupled with the increasing size of your baby, could cause serious discomfort and even limit your mobility. If you're having any kind of pelvic pain, talk to your healthcare provider about treatments. Though everyone may be telling you to get rest while you can, falling and staying asleep often becomes a challenge as you draw nearer to your due date. It's hard to get comfortable at night as your belly gets bigger, and the growing pressure on your bladder may wake you, again and again, to pee in the middle of the night. Though pregnancy insomnia can be hard to overcome, try these tricks to get better pregnancy sleep. `,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/392c0d743a630e35755e559734187ff5-615x410.jpg",
        textus: "This scan image shows the spine of the baby just over halfway through a pregnancy."
    },
    {
        id: 26,
        title: "week-26",
        image: "https://assets.babycenter.com/ims/2018/06/26-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 26",
        message: "At 26 weeks, your baby is inhaling and exhaling small amounts of amniotic fluid. This is good practice for breating.",
        fruit: "https://assets.babycenter.com/ims/2020/11/26-weeks-scallions_wide.jpg?width=722",
        size: "Your baby, now nearly 14 inches from head to heel and roughly 2 pounds, may be able to hear both your voice and the voices of people you talk to.",
        development: `Your baby can hear your voice and may even respond to it with changes in their heartbeat, breathing, and movement. If a noise is particularly loud, your baby may startle – and you might feel your baby move. If you're having a boy, his testicles have begun to descend into his scrotum – a trip that will take about two to three months.`,
        mom: "If your lower back is aching lately, you can thank both your growing uterus and hormonal changes that loosen your joints and ligaments. Roughly 60 percent of pregnant women have lower-back pain, which can make it hard to sleep or perform daily tasks. If your lower back is aching lately, you can thank both your growing uterus and hormonal changes that loosen your joints and ligaments. Roughly 60 percent of pregnant women have lower-back pain, which can make it hard to sleep or perform daily tasks.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/d9a82e4e1a7b5d8535d2901294504fb5-615x410.jpg",
        textus:"By this stage the baby can now swallow amniotic fluid and often gets the hiccups. On this scan picture you can see how far he opens his mouth."
    },
    {
        id: 27,
        title: "week-27",
        image: "https://assets.babycenter.com/ims/2018/06/27-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 27",
        message: "At 27 weeks pregnant, you may feel your baby hiccupping. Your baby is also opening and closing his/her eyes and even succing his/her finger",
        fruit: "https://assets.babycenter.com/ims/2020/11/27-weeks-cauliflower_wide.jpg?width=722",
        size: "Your baby is now as hefty as a head of cauliflower, weighing in at about 2 1/3 pounds and measuring roughly 14 1/2 inches.",
        development: `Your baby's eyes can now open and close! Your baby may move in response to light: If you shine a flashlight at your tummy, you might feel a burst of flutters and wiggles. Any tiny, rhythmic movements you feel are likely fetal hiccups. Each episode usually lasts only a few moments, and they're totally normal, so relax and enjoy the strange sensation. Your baby's lungs are making surfactant. This liquid substance helps the alveoli (tiny air sacs in the lungs) remain open, which makes it possible for your baby to breathe after birth.`,
        mom: `In later pregnancy, some women feel an unpleasant "creepy-crawly" sensation in their lower legs and an irresistible urge to move them while trying to relax or sleep. If this sensation is at least temporarily relieved when you move, you may have what's known as restless leg syndrome, or RLS. Many pregnant women deal with leaking urine, especially later in pregnancy. Hormonal changes cause the muscles in the pelvic floor to relax, so they give less support to your bladder. Also, your blood volume increases, which means your kidneys are processing more fluid and you have more urine.`,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/12fcc62aa6ac66030d5363760468cf23-615x410.jpg",
        textus: "In the last week of the second trimester (the third trimester begins at 28 weeks) the blood flow in the brain can be clearly seen."
    },
    {
        id: 28,
        title: "week-28",
        image: "https://assets.babycenter.com/ims/2018/06/28-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 28",
        message: "At 28 weeks, you are starting the last trimester. Your baby's eyes may be able to see light fitering in through your womb",
        fruit: "https://assets.babycenter.com/ims/2020/11/28-weeks-eggplant_wide.jpg?width=722",
        size: "Your baby now weighs about 2 2/3 pounds, is almost 15 inches long from head to heel, and can blink their eyes (which now sport lashes).",
        development: `Your baby's brain will triple in weight this trimester. The cerebrum will develop deep, convoluted grooves that provide extra surface area without taking up more room in the skull. Your baby's senses of hearing, smell, and touch are developed and functional. At 28 weeks, your baby's autonomic nervous system (which controls involuntary movements) is taking on new tasks. Specifically, it's starting to control your baby's body temperature and manage rhythmic breathing movements, which develop and strengthen your baby's lungs.`,
        mom: "Leg cramps during pregnancy tend to show up in the third trimester. They happen for a number of reasons: You're carrying extra weight, and you may have swelling in your legs (edema). If you're deficient in certain vitamins or not getting as much exercise, this might also contribute to leg pain. If you've noticed occasional blood in your stool, it's likely the result of hemorrhoids. Hemorrhoids are swollen blood vessels in the pelvic area which may cause light bleeding. Hemorrhoids during pregnancy are very common and are often the result of constipation, your growing uterus putting pressure on your veins, and hormonal changes.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/2d53503f562a07559f27045004d6926e-615x410.jpg",
        textus: "As well as the flow of blood, you can also see other fluids in a scan – in this case you can also see the urine stream of the baby. Although babies urinate into the amniotic fluid, it is highly sterile."
    },
    {
        id: 29,
        title: "week-29",
        image: "https://assets.babycenter.com/ims/2018/06/29-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 29",
        message: "At 29 weeks, you baby's muscles and lungs are maturing, and his/her head is growing to make room for the developing brain.",
        fruit: "https://assets.babycenter.com/ims/2020/11/29-weeks-butternut-squash_wide.jpg?width=722",
        size: "Your baby is about the size of a butternut squash, AND now weighs more than 3 pounds and is about 15 1/2 inches long from head to heel.",
        development: `Your baby's bones are soaking up lots of calcium as they harden, so be sure to drink your milk (or find another good source of calcium, such as cheese, yogurt, or enriched orange juice). About 250 milligrams of calcium are deposited in your baby's skeleton each day. A protective covering of myelin begins to form around your baby's nerves during this trimester, a process that will continue after your baby's born. Your baby's respiratory system is still developing. Their lungs are producing surfactant, a liquid that helps keep the alveoli open. By 35 weeks, your baby will be making enough surfactant to allow them to breathe air at birth.`,
        mom: "Getting enough iron during pregnancy is important for many reasons. You need iron for your growing baby and placenta, and it's essential for making hemoglobin, the protein in red blood cells that carries oxygen to other cells. (During pregnancy, you have almost 50 percent more blood than usual!) Low iron during pregnancy can lead to anemia.During the third trimester, you might experience regular cramping from round ligament pain and Braxton Hicks. (These can mimic the feeling of menstrual cramps.) If you're struggling with constipation, it might also cause some cramping. You might occasionally feel lightheaded or dizzy when you're pregnant because your cardiovascular system undergoes dramatic changes. Your heart rate goes up, your heart pumps more blood per minute, and the amount of blood in your body increases. In the second and third trimester, your growing uterus also puts pressure on veins and slows circulation to the lower half of your body.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/b3a7aba70be6c523ab41d10f70aeb272-615x410.jpg",
        textus: "A little foot can be seen pointing here, no doubt kicking his mum in the ribs!"
    },
    {
        id: 30,
        title: "week-30",
        image: "https://assets.babycenter.com/ims/2018/06/30-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 30",
        message: "At 30 weeks, your baby weights almost 3 pounds. You may be battling mood swings, clumsiness and fatigue",
        fruit: "https://assets.babycenter.com/ims/2020/11/30-weeks-cabbage_wide.jpg?width=722",
        size: "Your baby tips the scales this week at almost 3 1/2 pounds (like a large cabbage) and is almost 16 inches long from head to heel.",
        development: `Your baby's skin cells are making melanin, which gives skin its color. (The more melanin cells produce, the darker the skin.) But most melanin production doesn't happen until after birth. Your baby's permanent skin tone will be fully developed around 6 months old.Your baby can open their eyes wide, and may be able to see dim shapes. By 31 weeks, the pupils are able to constrict and expand, allowing the eyes to let in more or less light.`,
        mom: `Your belly button may be looking different now that you're 30 weeks pregnant. In your third trimester, your expanding uterus can put enough pressure on your abdomen to push your belly button out. And just like that, your "innie" turns into an "outie." Your belly button may also feel sensitive to the touch or uncomfortable when clothes rub against it. Later in the third trimester, a simple trip up the stairs may wear you out. As your pregnancy progresses, you may start to feel winded after doing ordinary tasks.`,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/134bd9e9d1f9bd987d681c600bae1b01-615x410.jpg",
        textus: "This 3D ultrasound shows a baby's face and the two little hands."
    },
    {
        id: 31,
        title: "week-31",
        image: "https://assets.babycenter.com/ims/2018/06/31-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 31",
        message: "At 31 weeks, you baby's kicks may be keeping you up at night. You may be feelin Braxton Hicks contractions.",
        fruit: "https://assets.babycenter.com/ims/2020/11/31-weeks-coconut_wide.jpg?width=722",
        size: "Your baby is a size of a coconut and now weighs almost 4 pounds, and measures about 16 1/2 inches from head to heel.",
        development: `Your baby's body is beginning to plump up as needed fat accumulates underneath their skin. For the rest of your pregnancy, your baby will be packing on the pounds in preparation for birth.Your baby can stretch, kick, and somersault – in fact, their dramatic motions may be keeping you up at night. Take comfort: All this fetal movement is a sign that your baby is active and healthy. Brain development kicks into high gear in the last trimester as your baby's brain triples in weight. Also, the cerebrum develops deep grooves that provide extra surface area without taking up more room in the skull.`,
        mom: `If you're seeing drops of a yellow or orange fluid leaking from your nipples (or in your bra cups), don't worry! This is colostrum, a high-protein, antibody-rich liquid that's the perfect first food for your newborn. Lower back pain is one of the most common pregnancy symptoms, and you may really be feeling it these days. It happens most in the second half of pregnancy, as your baby grows larger. As your uterus expands, it shifts your center of gravity and stretches your abdominal muscles, putting strain on your back. If you're feeling a sharp or dull pain that starts in your lower back and radiates down your buttocks and legs, you may have sciatica. This pain occurs when there's compression, inflammation, or irritation of the sciatic nerve, which runs from your lower spine to your buttocks and down the back of your legs.`,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/048857381c776b2a4f55f3e63845ebae-615x410.jpg",
        textus: "In this image you can see the baby's face and his eyes are slightly open – by 31 weeks babies open and close their eyes regularly."
    },
    {
        id: 32,
        title: "week-32",
        image: "https://assets.babycenter.com/ims/2018/06/32-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 32",
        message: "Your baby is plumping up! At 32 weeks, your expanding uterus may cause heartburn and shortness of breath.",
        fruit: "https://assets.babycenter.com/ims/2020/11/32-weeks-jicama_wide.jpg?width=722",
        size: "Your baby is taking up more and more space in your uterus, weighing in at about 4 1/3 pounds like a jicama and measuring nearly 17 inches from head to heel.",
        development: `our baby's body is stashing away important minerals such as iron, calcium, and phosphorus. The iron stores your baby builds now last for the first 6 months of life, until your little one starts eating solid foods.By next month, your baby's lungs will be fully formed. For now, your baby is practicing breathing by inhaling and exhaling amniotic fluid.If you're having a boy, his external genitalia is formed and his testicles have started descending to the scrotum. If you're having a girl, her uterus and ovaries are in place with all the eggs she'll have.`,
        mom: "While it's not a medical term, lightning crotch is an evocative phrase used to describe sharp pains in the pelvic area you may experience in late pregnancy. Some expecting moms have shooting pain through their groin and into their thigh. Others feel a burning or pins-and-needles sensation. Thankfully, it usually only lasts for a few seconds.A certain amount of edema (swelling) is normal during pregnancy, but excessive swelling may be a sign of a serious condition called preeclampsia. Be sure to call your provider if you have severe or sudden swelling of your feet or ankles, more than slight swelling of your hands, swelling in your face, or puffiness around your eyes.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/4816deea5af0f431064dc8e4728687e1-615x410.jpg",
        textus: "In this image you can see the penis of the baby boy."
    },
    {
        id: 33,
        title: "week-33",
        image: "https://assets.babycenter.com/ims/2018/06/33-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 33",
        message: "At 33 weeks, you may be waddling and having trouble getting comfy in bed. Your baby weighs a little over 4 pounds now.",
        fruit: "https://assets.babycenter.com/ims/2020/11/33-weeks-pineapple_wide.jpg?width=722",
        size: "Your baby is about the size of a pineapple. Measuring 17 1/3 inches from head to heel and weighing about 4 3/4 pounds, your baby is rapidly losing that wrinkled, alien look, and their skeleton is hardening.",
        development: `The bones in your baby's skull aren't fused together, which allows them to move and slightly overlap. This makes it easier for your baby to fit through the birth canal (the channel formed by your cervix, vagina, and vulva). The pressure on their head during birth is so intense that many babies are born with a pointy head! It's getting snug in your womb, so your baby isn't doing as many somersaults, but the amount of movement you feel should remain about the same. Your little one is rapidly losing that wrinkled look. Their baby skin is less red and transparent – it's becoming soft and smooth as your little one plumps up in preparation for birth.`,
        mom: "If you're feeling some achiness and even numbness in your fingers, wrists, and hands, you may have carpal tunnel syndrome. It happens when the median nerve – a major nerve in the hand that travels through the wrist and arm – is squeezed or compressed. You're more prone to it during pregnancy because of swelling in your hands and wrists. Swollen labia are a normal – if surprising – symptom during pregnancy. Increased blood flow, combined with added pressure from your growing uterus and hormonal changes, contribute to swelling in the lips that surround the opening of the vagina. If you're feeling forgetful, it makes sense: You've got a lot on your mind, and you may not be getting very good sleep. Stress and fatigue can interfere with your ability to concentrate.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/bb900c09bd4fcf5f6322b41a50bca468-615x410.jpg",
        textus: "You can clearly see the profile of the baby in this scan."
    },
    {
        id: 34,
        title: "week-34",
        image: "https://assets.babycenter.com/ims/2018/06/34-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 34",
        message: "At 34 weeks, you baby's central nervous system and lungs are maturing. Dizziness and fatigue may be slowing you down.",
        fruit: "https://assets.babycenter.com/ims/2020/11/34-weeks-cantaloupe_wide.jpg?width=722",
        size: "Your melon-sized munchkin now weighs about 5 1/4 pounds and is almost 18 inches long from head to heel.",
        development: `At 34 weeks, your baby's fingernails have grown to the end of their fingertips. Their toenails will reach the tip of their toes at 38 weeks. (Get those infant nail clippers ready!)Your baby is fattening up everywhere, and their arms and legs are starting to fill out beautifully. Your baby can respond to sounds, light, and touch. By next week, your baby's ears will be fully formed.`,
        mom: "It's normal to have vaginal discharge whether you're pregnant or not. Called leukorrhea, healthy discharge is milk-white or clear, has a mild smell, and can be thin or thick.Some vaginal discharge indicates a problem. Vaginal discharge that's green, smells unpleasant, causes pain or itching, or seems unusual in any other way could be a sign of infection or another issue.Toward the end of pregnancy, you might lose your mucus plug. If you do, you'll see an increased amount of vaginal discharge over the course of a few days, or a glob of thickened mucus that's clear, pinkish, brownish, or tinged with a bit of blood.You may wonder how you'll be able to tell the difference between vaginal discharge and amniotic fluid if your water breaks. Here are the main things to watch for: Amniotic fluid leaks out continuously (rather than sporadically), and is usually clear or slightly yellowish, watery, and odorless or slightly sweet-smelling.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/78bfacad9d819051ed7975f7a2b6a28a-615x410.jpg",
        textus: "Here you can see the baby's little ear, fully formed and getting ready to hear its first sounds outside the womb."
    },
    {
        id: 35,
        title: "week-35",
        image: "https://assets.babycenter.com/ims/2018/06/35-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 35",
        message: "At 35 weeks, baby is too snug in your womb to do a lot of somersaults, but you still feel frequent movements.",
        fruit: "https://assets.babycenter.com/ims/2020/11/35-weeks-honeydew_wide.jpg?width=722",
        size: "Your baby is about the size of a honeydew melon, now weighing in at 5 3/4 pounds and measuring more than 18 inches, doesn't have much room to maneuver in your belly.",
        development: `Your baby is cushioned and protected by about a quart of amniotic fluid. It increases during pregnancy until about 36 weeks, then gradually decreases until you give birth.Your baby's kidneys are fully developed now – they've actually been making urine since you were 13 weeks pregnant. (Your baby pees into the amniotic fluid!) Your baby's first bowel movement (called meconium) is building up in their intestines.Your baby now has distinct sleeping patterns. You may start to recognize these cycles: You'll probably feel your baby moving more when they're awake and less when they're asleep.`,
        mom: "Your uterus now reaches up under your rib cage. It's crowding your internal organs, which is one reason why you may be dealing with increased heartburn (also called acid indigestion or acid reflux) and other gastrointestinal issues such as gas and bloating now. During the second half of pregnancy, it's common to have vision changes like blurry vision and dry eye. An estimated 14 percent of all women, in fact, report becoming more nearsighted or having blurry vision during pregnancy. These symptoms are considered normal, and they're nothing to be concerned about unless they become severe. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/c58dd70dffdfca397c96ae4d1f28e3a0-615x410.jpg",
        textus: "In this picture you can see the child from above the head. The bright points in the image is hair floating in the amniotic fluid."
    },
    {
        id: 36,
        title: "week-36",
        image: "https://assets.babycenter.com/ims/2018/06/36-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 36",
        message: `Your baby is gaining about an ounce a day now that you are 36 weeks pregnant. You may feel the baby "drop" down into your pelvis soon.`,
        fruit: "https://assets.babycenter.com/ims/2020/11/36-weeks-lettuce_wide.jpg?width=722",
        size: "Your not-so-little lettuce now measures more than 18 1/2 inches from head to heel and weighs more than 6 pounds (and is still packing it on at a rate of about an ounce a day).",
        development: `Your baby's lungs are ready for the outside world! When your newborn inhales for the first time – within about 10 seconds after delivery – their lungs expand, and any fluid remaining in the alveoli is replaced with air. Your baby's bones are hardening, though they're still softer than an adult's. Some are made entirely of flexible cartilage that's gradually replaced by bone throughout childhood. Fun fact: Newborns are born with more than 275 bones, but adults have only 206. That's because some bones fuse together over time.`,
        mom: "Mild cramping throughout pregnancy is normal and usually harmless. Cramping can be caused by issues like bloating, constipation, and round ligament pain. At this point in pregnancy, you may have cramping from Braxton Hicks, or false labor contractions, as well. Cramping can also be an early sign of labor. Call your provider if: You feel contractions accompanied by lower back pain. You feel more than six contractions an hour (even if they don't hurt). The contractions are coming at regular intervals. You also have vaginal discharge or bleeding. You have any other signs of premature labor.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/47a5e0fdf794ce627c2e5d24bff2caa8-615x410.jpg",
        textus: "This scan shows the genital area of a baby girl."
    },
    {
        id: 37,
        title: "week-37",
        image: "https://assets.babycenter.com/ims/2018/06/36-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 37",
        message: "At 37 weeks, you baby's brain and lungs continue to mature. You may have more vaginal discarge and occasional contractions.",
        fruit: "https://assets.babycenter.com/ims/2020/11/37-weeks-collard-greens_wide.jpg?width=722",
        size: "Your baby is about the length of a bunch of Swiss chard. It measures roughly 19 inches from head to heel and weighs about 6 2/3 pounds.",
        development: `Many babies have a full head of hair at birth, with locks from 1/2 inch to 1 1/2 inches long. Of course, some babies sport only peach fuzz. Don't be surprised if your baby's hair isn't the same color as yours. Also, it may fall out within the first six months and grow back a different color and texture! You may not see your baby's true eye color at birth. Some babies are born with their final eye color, but other newborns have dark blue or slate-gray eyes that gradually change to blue, green, hazel, or brown over the first year.`,
        mom: "You might notice an increase in vaginal discharge by 37 weeks, and it may be clear, pink, or even slightly bloody. You may see your mucus plug, the thick clump of mucus in your cervical canal that prevented bacteria from getting into your uterus during pregnancy. Once you're getting close to labor, or in labor, the mucus plug could come out gradually or all at once. Keep monitoring your baby's kicks, and let your provider know immediately if you notice a decrease. Though your baby's quarters are getting cozy, they should still be as active as before. Since they're getting stronger, their movements might become more noticeable, or even painful.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/64d2cb0a747dd401a2249f062cff2961-615x410.jpg",
        textus: "Again, you can see the profile – the baby's face is fully formed now, and if it was born at this point, he would no longer be classed premature."
    },
    {
        id: 38,
        title: "week-38",
        image: "https://assets.babycenter.com/ims/2018/06/38-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 38",
        message: "Your baby has a firm grasp, which you'll soon be able to test in person! It is wise to watch for signs of preeclamsia",
        fruit: "https://assets.babycenter.com/ims/2020/11/38-weeks-leek_wide.jpg?width=722",
        size: "Your lanky leek is now about 19 1/2 inches long from head to heel and weighs more than 7 pounds.",
        development: `Your baby's fingernails and toenails are fully formed – toenails have reached the tips of your baby's toes, and their fingernails may extend beyond their fingertips. Your baby may need a nail trim soon after birth, so get those baby nail clippers ready! Your baby is ready for their first pictures: They have a nice layer of fat for smooth skin, they've shed most of their lanugo (except perhaps some on their upper arms and shoulders), and they may have more hair on their head, too.`,
        mom: "Some swelling in your feet and ankles is normal during these last weeks, but call your doctor or midwife without delay if you notice excessive or sudden swelling of your feet or ankles, more than slight swelling of your hands, any swelling in your face or puffiness around your eyes, or if you have a sudden weight gain. These can be symptoms of a serious condition called preeclampsia. The best way to counteract swelling is to relieve some of the pressure. Move around regularly and avoid sitting or standing for too long. When you can, elevate your feet. Something as simple as a stool to rest your feet on at work, or a pillow under your feet in bed, can make a big difference. ",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/6f1d760e03798bb06deef73d031f875e-615x410.jpg",
        textus: "You can see the baby sucking his thumb in this picture."
    },
    {
        id: 39,
        title: "week-39",
        image: "https://assets.babycenter.com/ims/2018/06/39-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 39",
        message: "At 39 weeks, your bay is full term and waiting to greet the world! If your water breaks, call your healthcare provider!",
        fruit: "https://assets.babycenter.com/ims/2020/11/39-weeks-watermelon_wide.jpg?width=722",
        size: "Your baby is about the size of a mini-watermelon. It now weighs about 7 1/2 pounds and is nearly 20 inches long from head to heel.",
        development: `Your little one continues to build a layer of fat to help control their body temperature after birth. It's likely that your baby already measures about 20 inches and weighs just over 7 pounds. (Boys tend to be slightly heavier than girls.) Your baby has a firm grasp, which you'll soon be able to test when you hold their hand for the first time! Your baby also has coordinated reflexes, can turn their head, and will be able to see your face once they're born. Newborns can see about 6 to 10 inches away.`,
        mom: "Keep paying attention to your baby's movements, and let your doctor or midwife know right away if they seem to decrease. At a prenatal checkup, your provider might do an internal exam to see whether your cervix has started ripening: softening, effacing (thinning out), and dilating (opening). But even with this knowledge, there's still no way to predict exactly when your baby is coming. Call your provider if you think your water may have broken. When the amniotic sac that surrounds your baby ruptures, sometimes there's a big gush of fluid, but oftentimes there's only a small burst or a slow leak. Call even if you're not sure or only suspect you have a leak. If your water breaks but contractions don't start soon, you may be induced. That's because once your amniotic sac has ruptured, you and your baby are at increased risk of infection.",
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/5453b93b600cdd8062a95bd39f2553e0-615x410.jpg",
        textus: "In this image you can see the four chambers of the heart and heart valves."
    },
    {
        id: 40,
        title: "week-40",
        image: "https://assets.babycenter.com/ims/2018/06/40-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 40",
        message: "At 40 weeks, you baby is the size of a small pumpkin! Don't worry if you're still pregnant - it's common to go past you due date.",
        fruit: "https://assets.babycenter.com/ims/2020/11/40-weeks-pumpkin_wide.jpg?width=722",
        size: "Your little pumpkin could arrive any day now, if they aren't here already. The average newborn weighs about 8 pounds and is about 20 inches long.",
        development: `Babies of all ethnicities are born with reddish-purple skin that changes to pinkish-red in a day or so. The pink tint comes from the red blood vessels that are visible through your baby's skin. Because your baby's blood circulation is still maturing, their hands and feet may be bluish for a few days. Babies of darker-skinned parents typically have lighter skin that gains pigment over time. Around 6 months old, your baby's skin will reach its permanent color. Your baby's skull isn't one large bone, like an adult's. It starts out as separate bones joined by flexible tissue. After your baby is born, you'll be able to feel the soft spots between the bones, called fontanels, on the top and back of your newborn's head.`,
        mom: `At 40 weeks, you're probably very familiar with Braxton Hicks contractions. But how can you tell so-called "false labor" from the real thing? There are some easy ways to tell the difference between Braxton Hicks and real labor contractions. For starters, Braxton Hicks are usually not painful, and they don't get closer together. If you drink water and rest, they'll probably stop, at least for now. You'll feel Braxton Hicks on the front of your belly most often, whereas real contractions often start in the back and radiate around to the front.Unlike Braxton Hicks, real contractions are painful. They'll arrive at regular intervals, getting closer together and more intense over time. And real contractions will persist, even if you lie down, take a bath, or find another way to relax. Once you've started having real contractions, follow your provider's advice about when to go to the hospital for labor. Usually, it's time to go when you've had contractions at regular intervals (such as every four or five minutes) that last about a minute each, for an hour or more.`,
        pictureus: "https://www.netmums.com/wp-content/uploads/netmums/2023/08/8b51702e4cdbb3ffc22342cb145bf798-615x410.jpg",
        textus: "In this image you can see the baby holding his hand to his face."
    },
    {
        id: 41,
        title: "week-41",
        image: "https://assets.babycenter.com/ims/2018/06/41-weeks-pregnant_4x3.png?width=1026",
        heading: "Week 41",
        message: " At 41 weeks, you'll go into labor or to be induced soon. Your baby should remain active right up until delivery",
        fruit: "https://assets.babycenter.com/ims/2020/11/40-weeks-pumpkin_wide.jpg?width=722",
        size: "Still around the size of a pumpkin, not much else has changed since last week, to be honest. According to estimates, they'll weigh 8.35 pounds and be 20.39 inches long. (Of course, this may be way off for your individual baby.)",
        development: `Your baby is "late term" – which means they've been camping out in your womb for a long time. They may be larger than the average baby. Also, they may have lost most of their vernix, which is the waxy, white coating that stops their skin from drying out in the amniotic fluid.It's hard not to be anxious when your due date comes and goes and you're still hugely pregnant. But fear not – you won't be pregnant forever. When labor begins, digestion slows or stops, and you may feel sick to your stomach. Some women report feeling nauseated during labor, and others say they were nauseated a day or two beforehand. More often, nausea happens during active labor.`,
        mom: "For safety reasons, your doctor or midwife will recommend inducing labor if your baby isn't born this week. Providers won't let you go more than two weeks past your due date because it raises the risk of complications. If this is your first baby, you may have been offered a sweep last week. If you’ve had a baby before, you should be offered it this week. A sweep is a simple procedure that can help to kick-start labour and reduce the need for medication to induce your labour. It’s a bit like a smear test, though it can be more uncomfortable.During a sweep, you’ll be asked to lie on your back, propped up with pillows. Your midwife or doctor will insert a single finger into your cervix, using a circular, ‘sweeping’ motion." ,
        pictureus: "https://th.bing.com/th/id/R.6091fa06af2d7ba02873ee9f668a1393?rik=ef1L6pesaFqQLg&riu=http%3a%2f%2finfobaby.org%2fwp-content%2fuploads%2f218-d0b08c3d222b5cee36af2daabf26aa0b.jpg&ehk=fTfwkKnKSiypi9YN6CU25asFpyCjM3UOS98jIznq9%2b4%3d&risl=&pid=ImgRaw&r=0",
        textus: "Studies show that most babies arrive within two weeks either side of the due date, so it’s probably not long to go now! "
    }






    
]
export default PregWeeks;